language: bash

services:
  - docker

before_install:
- docker images
- docker pull summergift/csp_test:v1.0
- docker cp csp_build.py summergift/csp_test:v1.0:/rt-thread
- docker run -it summergift/csp_test:v1.0 bash -c
  "scons --version && pytest --version
   && cd /rt-thread && git clone https://gitee.com/SummerGift/hello_test.git
   && chmod a+x hello_test/build.sh && hello_test/build.sh && python csp_build.py"
