language: bash

services:
  - docker

before_install:
  - docker pull summergift/csp_test:v1.0
  - docker run -v "`pwd`:/rt-thread/csp_build" -it summergift/csp_test:v1.0 bash -c "python /rt-thread/csp_build/csp_build.py"
